PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS Document (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Document_History (
    did TEXT NOT NULL,
    modified_at DATETIME NOT NULL,
    FOREIGN KEY (did) REFERENCES Document(id) ON DELETE CASCADE ON UPDATE CASCADE   
);

CREATE TABLE IF NOT EXISTS Category (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS File (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    cid TEXT NOT NULL,
    author TEXT NOT NULL,
    description TEXT NOT NULL,
    did TEXT NOT NULL,
    view INTEGER DEFAULT 0,
    FOREIGN KEY (did) REFERENCES Document(id) ON DELETE CASCADE ON UPDATE CASCADE
    FOREIGN KEY (cid) REFERENCES Category(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS File_History (
    fid TEXT NOT NULL,
    modified_at DATETIME NOT NULL,
    FOREIGN KEY (fid) REFERENCES File(id) ON DELETE CASCADE ON UPDATE CASCADE
);

COMMIT;